package com.PicServlet.gwzd;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PicServerService service = new PicServerService();
 * PicServerDelegate portType = service.getPicServerPort();
 * portType.login(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PicServerService", targetNamespace = "http://zxl.pic.com/", wsdlLocation = "http://192.168.1.66:5042/ImageRecognition/PicServerPort?wsdl")
public class PicServerService extends Service {

	private final static URL PICSERVERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.PicServlet.gwzd.PicServerService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.PicServlet.gwzd.PicServerService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.1.66:5042/ImageRecognition/PicServerPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.66:5042/ImageRecognition/PicServerPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PICSERVERSERVICE_WSDL_LOCATION = url;
	}

	public PicServerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PicServerService() {
		super(PICSERVERSERVICE_WSDL_LOCATION, new QName("http://zxl.pic.com/",
				"PicServerService"));
	}

	/**
	 * 
	 * @return returns PicServerDelegate
	 */
	@WebEndpoint(name = "PicServerPort")
	public PicServerDelegate getPicServerPort() {
		return super.getPort(new QName("http://zxl.pic.com/", "PicServerPort"),
				PicServerDelegate.class);
	}

}
