package com.PicServlet.gwzd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PicServerDelegate", targetNamespace = "http://zxl.pic.com/")
public interface PicServerDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Login")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Login", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.Login")
	@ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.LoginResponse")
	public String login(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetPicByPath")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "GetPicByPath", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.GetPicByPath")
	@ResponseWrapper(localName = "GetPicByPathResponse", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.GetPicByPathResponse")
	public String getPicByPath(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod(operationName = "UpLoadAlarm")
	@RequestWrapper(localName = "UpLoadAlarm", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.UpLoadAlarm")
	@ResponseWrapper(localName = "UpLoadAlarmResponse", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.UpLoadAlarmResponse")
	public void upLoadAlarm(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetBase64Pic_New")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "GetBase64Pic_New", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.GetBase64PicNew")
	@ResponseWrapper(localName = "GetBase64Pic_NewResponse", targetNamespace = "http://zxl.pic.com/", className = "com.PicServlet.gwzd.GetBase64PicNewResponse")
	public String getBase64PicNew(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
